### PR TITLE
Fix attach onDidCloseTerminal() listener once

### LINKED ISSUE #70: `onDidCloseTerminal` is applied multiple times
In the [src/client/run.ts][runts] an event listener is applied every time a user run a V file:
```ts
	vscode.window.onDidCloseTerminal(term => {
		if (term.name == 'V') { 
			vRunTerm = null; 
		} 
	});
```
The listener should be applied if nessessary (e.g. when assigning a value to `vRunTerm` variable).

[runts]: https://github.com/0x9ef/vscode-vlang/blob/b247c9fce1dbb660be7ca8bd4d37e9c42a19240a/src/client/run.ts#L13

### PR DESCRIPTION
**Pull request by dhonx**
Fixes #70

### CODE REVIEW

File: src/client/extension.ts [hunk 1]
```diff
@@ -15,8 +16,9 @@ export function activate(context: vscode.ExtensionContext) {
 	let testFile = vscode.commands.registerCommand('v.test.file',commands.testFile);
 	let testPackage = vscode.commands.registerCommand('v.test.package',commands.testPackage);
 	let playground = vscode.commands.registerCommand('v.playground',commands.playground);
-	
+
 	registerFormatter();
+	vscode.window.onDidCloseTerminal(handle)
```
Comment (alexesprit) [inline src/client/extension.ts]: You could also replace it with a function, e.g. `attachTerminalCloseListener`, and put the block:
```ts
// run.ts
export function attachTerminalCloseListener() {
	vscode.window.onDidCloseTerminal(term => {
		if (term.name == 'V') { 
			vRunTerm = null; 
		} 
	});
}
```
inside that new function.

Comment (dhonx) [reply src/client/extension.ts]: Great idea @alexesprit !!!
